#!/usr/bin/with-contenv bash
# S6 service script

ARCH=$(uname -m)

echo "[Technitium DNS] Erkannte Architektur: $ARCH"

case "$ARCH" in
  armv7l)
    URL="https://download.technitium.com/dns/dns-server-linux-arm.tar.gz"
    ;;
  aarch64)
    URL="https://download.technitium.com/dns/dns-server-linux-arm64.tar.gz"
    ;;
  *)
    echo "[Technitium DNS] Nicht unterstützte Architektur: $ARCH"
    exit 1
    ;;
esac

echo "[Technitium DNS] Lade von $URL"
curl -sSL "$URL" | tar xz -C /opt

echo "[Technitium DNS] Starte Server..."
exec /opt/start.sh
