#!/usr/bin/with-contenv bash
# Starte Technitium DNS

source /opt/scripts/common.sh
source /opt/scripts/init.sh

log_info "Starte Technitium DNS Server..."

# Standardstart aus dem offiziellen Image
exec /app/dns/dnsserver
