#!/usr/bin/with-contenv sh
. /opt/scripts/common.sh
. /opt/scripts/init.sh

log_info "Starte Technitium DNS Server (Custom Image)..."
log_info "Persistenter Ordner: /data"

# Technitium direkt mit AppDataPath starten
exec /app/dns/dnsserver --appdatafolder /data
