#!/usr/bin/with-contenv sh
set -e

# Persistent Folder /data nutzen
if [ ! -d /data ]; then
    mkdir -p /data
fi

# /etc/dns auf /data mappen
if [ -d /etc/dns ] && [ ! -L /etc/dns ]; then
    rm -rf /etc/dns
    ln -s /data /etc/dns
fi

echo "[INFO] Config folder linked: /etc/dns -> /data"

# Technitium DNS starten
exec /app/dnsserver